wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: Val MAE
      6:
      - 3
      7:
      - 1
    - 1: Val RMSE
      6:
      - 3
      7:
      - 1
    python_version: 3.7.0
    start_time: 1645809299
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 7
      - 15
      4: 3.7.0
      5: 0.12.10
      8:
      - 5
